name: Compilar Aplicación Multiplataforma

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Generar Estructura Nativa Android
        run: |
          mkdir temp_code
          mv lib temp_code/
          mv pubspec.yaml temp_code/
          flutter create --platforms=android --project-name=iglesia_moral_calatrava .
          rm -rf lib pubspec.yaml
          mv temp_code/lib .
          mv temp_code/pubspec.yaml .
        shell: bash

      - name: Instalar Dependencias
        run: flutter pub get

      - name: Compilar APK de Producción
        run: flutter build apk --release

      - name: Subir Instalador Android (APK)
        uses: actions/upload-artifact@v4
        with:
          name: App_Iglesia_Android_Instalable
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Generar Estructura Nativa Windows
        run: |
          mkdir temp_code
          mv lib temp_code/
          mv pubspec.yaml temp_code/
          flutter create --platforms=windows --project-name=iglesia_moral_calatrava .
          rm -rf lib pubspec.yaml
          mv temp_code/lib .
          mv temp_code/pubspec.yaml .
        shell: bash

      - name: Instalar Dependencias
        run: flutter pub get

      - name: Compilar Ejecutable Windows
        run: flutter build windows --release

      - name: Subir Instalador Windows (PC)
        uses: actions/upload-artifact@v4
        with:
          name: App_Iglesia_Windows_PC
          path: build/windows/runner/Release/
